public abstract class AbstractSum {
public abstract void sumOfTwo(integer a, integer b);
public abstract void sumOfThree(integer a, integer b,integer c);
public abstract void multipleOfTwo(integer a,integer b);
public abstract void divisionOfTwo(integer a,integer b);
 //public abstract void sortNumber(List<integer> number);   
    public void display(){
        system.debug('Results of the methods');
    }
}